// Export pages
export '/pages/quiz/quizzes/quiz_hitze/quiz_hitze_widget.dart'
    show QuizHitzeWidget;
export '/pages/home/home_widget.dart' show HomeWidget;
export '/pages/hitze/memory/memory_widget.dart' show MemoryWidget;
export '/pages/klima_overview/klima_overview_widget.dart'
    show KlimaOverviewWidget;
export '/pages/hitze/hitze_geburtenrate/hitze_geburtenrate_widget.dart'
    show HitzeGeburtenrateWidget;
export '/pages/hitze/hitze_tiere/hitze_tiere_widget.dart' show HitzeTiereWidget;
export '/pages/hitze/hitze_lebensmittel/hitze_lebensmittel_widget.dart'
    show HitzeLebensmittelWidget;
export '/pages/hitze/hitze_infektionen/hitze_infektionen_widget.dart'
    show HitzeInfektionenWidget;
export '/pages/hitze/hitze_mental_health/hitze_mental_health_widget.dart'
    show HitzeMentalHealthWidget;
export '/pages/hitze/hitze_mortalitaet/hitze_mortalitaet_widget.dart'
    show HitzeMortalitaetWidget;
export '/pages/hitze/hitze_dir_indir_folgen/hitze_dir_indir_folgen_widget.dart'
    show HitzeDirIndirFolgenWidget;
export '/pages/quiz/antwort_seiten/antwort_hitze/antwort_hitze_widget.dart'
    show AntwortHitzeWidget;
export '/pages/quiz/ergebniss/ergebniss_widget.dart' show ErgebnissWidget;
export '/pages/hitze/hitze_generell/hitze_generell_widget.dart'
    show HitzeGenerellWidget;
export '/pages/naturkatastrophen/naturkatastrophen_generell/naturkatastrophen_generell_widget.dart'
    show NaturkatastrophenGenerellWidget;
export '/pages/naturkatastrophen/naturkatastrophen_geburtenrate/naturkatastrophen_geburtenrate_widget.dart'
    show NaturkatastrophenGeburtenrateWidget;
export '/pages/naturkatastrophen/naturkatastrophen_tiere/naturkatastrophen_tiere_widget.dart'
    show NaturkatastrophenTiereWidget;
export '/pages/naturkatastrophen/naturkatastrophen_infektionen/naturkatastrophen_infektionen_widget.dart'
    show NaturkatastrophenInfektionenWidget;
export '/pages/naturkatastrophen/naturkatastrophen_mental_health/naturkatastrophen_mental_health_widget.dart'
    show NaturkatastrophenMentalHealthWidget;
export '/pages/naturkatastrophen/naturkatastrophen_mortalitt/naturkatastrophen_mortalitt_widget.dart'
    show NaturkatastrophenMortalittWidget;
export '/pages/naturkatastrophen/naturkatastrophen_folgen/naturkatastrophen_folgen_widget.dart'
    show NaturkatastrophenFolgenWidget;
export '/pages/c_o2_pages/c_o2_generell/c_o2_generell_widget.dart'
    show CO2GenerellWidget;
export '/pages/c_o2_pages/c_o2_tiere/c_o2_tiere_widget.dart'
    show CO2TiereWidget;
export '/slide_puzzle/slide_puzzle/slide_puzzle_widget.dart'
    show SlidePuzzleWidget;
export '/pages/inhala_gase/inhala_gase_treibhauseffekt/inhala_gase_treibhauseffekt_widget.dart'
    show InhalaGaseTreibhauseffektWidget;
export '/pages/klimaneutrales_k_h/klimaneutrales_krankenhaus/klimaneutrales_krankenhaus_widget.dart'
    show KlimaneutralesKrankenhausWidget;
export '/pages/fussabdruck_k_h/fussabdruck_c_o2/fussabdruck_c_o2_widget.dart'
    show FussabdruckCO2Widget;
export '/pages/abfall/abfallmanagement_k_h/abfallmanagement_k_h_widget.dart'
    show AbfallmanagementKHWidget;
export '/pages/fussabdruck_k_h/fussabdruck_treibhauseffekt/fussabdruck_treibhauseffekt_widget.dart'
    show FussabdruckTreibhauseffektWidget;
export '/pages/quiz/quizzes/quiz_geburt/quiz_geburt_widget.dart'
    show QuizGeburtWidget;
export '/pages/quiz/antwort_seiten/antwort_geburt/antwort_geburt_widget.dart'
    show AntwortGeburtWidget;
export '/pages/game_overview/game_overview_widget.dart' show GameOverviewWidget;
export '/pages/abfall/abfallmanagement_reduce/abfallmanagement_reduce_widget.dart'
    show AbfallmanagementReduceWidget;
export '/pages/abfall/abfallmanagement_reuse/abfallmanagement_reuse_widget.dart'
    show AbfallmanagementReuseWidget;
export '/pages/abfall/abfallmanagement_recycle/abfallmanagement_recycle_widget.dart'
    show AbfallmanagementRecycleWidget;
export '/pages/abfall/abfallmanagement_rethink/abfallmanagement_rethink_widget.dart'
    show AbfallmanagementRethinkWidget;
export '/pages/abfall/abfallmanagement_research/abfallmanagement_research_widget.dart'
    show AbfallmanagementResearchWidget;
export '/pages/abfall/zuordnung/zuordnung_widget.dart' show ZuordnungWidget;
export '/pages/quiz/antwort_seiten/antwort_klima_auf_gesundheit/antwort_klima_auf_gesundheit_widget.dart'
    show AntwortKlimaAufGesundheitWidget;
export '/pages/quiz/antwort_seiten/antwort_k_h_g_w/antwort_k_h_g_w_widget.dart'
    show AntwortKHGWWidget;
export '/pages/quiz/antwort_seiten/antwort_mental/antwort_mental_widget.dart'
    show AntwortMentalWidget;
export '/pages/quiz/antwort_seiten/antwort_naturkatastropen/antwort_naturkatastropen_widget.dart'
    show AntwortNaturkatastropenWidget;
export '/pages/quiz/antwort_seiten/antwort_tiere/antwort_tiere_widget.dart'
    show AntwortTiereWidget;
export '/pages/quiz/quizzes/quiz_klima_auf_gesundheit/quiz_klima_auf_gesundheit_widget.dart'
    show QuizKlimaAufGesundheitWidget;
export '/pages/quiz/quizzes/quiz_k_h_g_w/quiz_k_h_g_w_widget.dart'
    show QuizKHGWWidget;
export '/pages/quiz/quizzes/quiz_mental/quiz_mental_widget.dart'
    show QuizMentalWidget;
export '/pages/quiz/quizzes/quiz_tiere/quiz_tiere_widget.dart'
    show QuizTiereWidget;
export '/pages/quiz/quizzes/quiz_naturkatastrophen/quiz_naturkatastrophen_widget.dart'
    show QuizNaturkatastrophenWidget;
export '/pages/naturkatastrophen/tsunamis_mortalitaet/tsunamis_mortalitaet_widget.dart'
    show TsunamisMortalitaetWidget;
export '/pages/naturkatastrophen/waldbrnde_mortalitaet/waldbrnde_mortalitaet_widget.dart'
    show WaldbrndeMortalitaetWidget;
export '/pages/c_o2_pages/c_o2_lebensmittel/c_o2_lebensmittel_widget.dart'
    show CO2LebensmittelWidget;
export '/pages/c_o2_pages/c_o2_mortalitaet/c_o2_mortalitaet_widget.dart'
    show CO2MortalitaetWidget;
export '/videos/videos/videos_widget.dart' show VideosWidget;
export '/videos/hitze_videos/hitze_videos_widget.dart' show HitzeVideosWidget;
export '/videos/hitze_videos2/hitze_videos2_widget.dart'
    show HitzeVideos2Widget;
export '/videos/naturkatastrophen_und_infektionen/naturkatastrophen_und_infektionen_widget.dart'
    show NaturkatastrophenUndInfektionenWidget;
export '/videos/naturkatastrophen_generell_video/naturkatastrophen_generell_video_widget.dart'
    show NaturkatastrophenGenerellVideoWidget;
export '/videos/c_o2_tiere_video/c_o2_tiere_video_widget.dart'
    show CO2TiereVideoWidget;
export '/videos/naturkatastrophen_geburtenrate_video/naturkatastrophen_geburtenrate_video_widget.dart'
    show NaturkatastrophenGeburtenrateVideoWidget;
export '/videos/naturkatastrophen_tiere_video/naturkatastrophen_tiere_video_widget.dart'
    show NaturkatastrophenTiereVideoWidget;
export '/videos/hitze_tiere_video/hitze_tiere_video_widget.dart'
    show HitzeTiereVideoWidget;
export '/videos/hitze_geburtenrate_video/hitze_geburtenrate_video_widget.dart'
    show HitzeGeburtenrateVideoWidget;
export '/videos/c_o2_allgemein_video/c_o2_allgemein_video_widget.dart'
    show CO2AllgemeinVideoWidget;
export '/videos/oekologischer_fussabdruck_video/oekologischer_fussabdruck_video_widget.dart'
    show OekologischerFussabdruckVideoWidget;
export '/videos/abfallmanagement_k_h_video/abfallmanagement_k_h_video_widget.dart'
    show AbfallmanagementKHVideoWidget;
export '/videos/abfallmanagement5_rs_video/abfallmanagement5_rs_video_widget.dart'
    show Abfallmanagement5RsVideoWidget;
export '/videos/anastaetika_video/anastaetika_video_widget.dart'
    show AnastaetikaVideoWidget;
export '/videos/klimaneutrale_k_h_video/klimaneutrale_k_h_video_widget.dart'
    show KlimaneutraleKHVideoWidget;
